<a href="https://colab.research.google.com/github/tpiedrahita-byte/sys2025/blob/main/Copy_of_4_IntroNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np # importar libreria numpy
x = 30 #tipo int
y = 36.5 #tipo float

print(type(x),type(y)) #imprimir en pantalla

<class 'int'> <class 'float'>


In [3]:
xv = np.array([0,-2.5,10]) #crear array tipo vector
xv

array([ 0. , -2.5, 10. ])

#Listas vs numpy array

Las listas pueden contener, números, strings, y en general objetos.
Los array de numpy están pensados para procesar números (matrices, tensores)

In [4]:
xl = [0,-2,0.5]
xl

[0, -2, 0.5]

In [5]:
xl = ['Brian Patiño',0.5, 2] #lista de tres elementos con un string, un flotante y un entero
xl

['Brian Patiño', 0.5, 2]

#Tamaños, indexación y graficar numpy array

In [6]:
xv.shape # vector con 3 elementos - > shape retorna la forma (tamaño del arreglo)

(3,)

In [7]:
xm = np.array([[0,-2.5,10,4],[6,47,70,2],[8,10.2,-698,-0.9]]) #cada lista de números es tratada como una fila de la matriz
xm

array([[   0. ,   -2.5,   10. ,    4. ],
       [   6. ,   47. ,   70. ,    2. ],
       [   8. ,   10.2, -698. ,   -0.9]])

In [8]:
xm.shape

(3, 4)

# En python se indexa desde 0

In [9]:
xv = np.array([-6,5,4.2,3,8,50,16])
print(xv,xv.shape,xv[0])

[-6.   5.   4.2  3.   8.  50.  16. ] (7,) -6.0


# En Python, cuando se indexa por rangos de valores, no se incluye el último elemento

In [10]:
xv[1:5] # x[t_0] # no se incluye el elemento 5 que equivale a x[5] = 50

array([5. , 4.2, 3. , 8. ])

Cuando se piden todos los elementos hasta el final con el operador : si se incluye el último elemento

In [11]:
# desde el segundo elemento hasta el ultimo
print(xv)
print(xv[1:])

[-6.   5.   4.2  3.   8.  50.  16. ]
[ 5.   4.2  3.   8.  50.  16. ]


In [12]:
#desde antes del tercer elmento hasta el principio
print(xv)
print(xv[:3])

[-6.   5.   4.2  3.   8.  50.  16. ]
[-6.   5.   4.2]


# Para matrices se extiende la misma sintaxis para indexar vectores, pero separando la indexación por filas y por columnas

In [13]:
print(xm)

[[   0.    -2.5   10.     4. ]
 [   6.    47.    70.     2. ]
 [   8.    10.2 -698.    -0.9]]


In [14]:
xm[0:2,:2]

array([[ 0. , -2.5],
       [ 6. , 47. ]])

In [15]:
xm[0:2,0]

array([0., 6.])

In [16]:
xm[0,1:]

array([-2.5, 10. ,  4. ])

In [17]:
np.diag(xm)#diagonal del arreglo (matriz)

array([   0.,   47., -698.])

#Vectores

Un vector es una secuencia de valores numéricos. En Python, podemos representar un vector utilizando una lista de números. Por ejemplo, el siguiente código crea un vector con los valores 1, 2 y 3:

In [18]:
vector = [1, 2, 3]

Podemos acceder a cada elemento del vector utilizando su índice. El índice del primer elemento es 0, el índice del segundo elemento es 1, y así sucesivamente. Por ejemplo, para acceder al segundo elemento del vector, podemos utilizar el siguiente código:

In [19]:
segundo_elemento = vector[1]

También podemos utilizar la función len para obtener la longitud del vector:

In [20]:
longitud = len(vector)

Además, podemos realizar operaciones aritméticas con vectores utilizando bucles for. Por ejemplo, el siguiente código suma dos vectores indexando las listas:

In [21]:
vector1 = [1, 2, 3]
vector2 = [4, 5, 6]

resultado = []
for i in range(len(vector1)):
    suma = vector1[i] + vector2[i]
    resultado.append(suma)

#Matrices

Una matriz es una tabla de valores numéricos. En Python, podemos representar una matriz utilizando una lista de listas. Cada lista interna representa una fila de la matriz. Por ejemplo, el siguiente código crea una matriz de 2 filas y 3 columnas:

In [22]:
matriz = [[1, 2, 3], [4, 5, 6]]

Podemos acceder a cada elemento de la matriz utilizando su índice de fila y columna. El índice de la primera fila es 0, el índice de la segunda fila es 1, y así sucesivamente. El índice de la primera columna es 0, el índice de la segunda columna es 1, y así sucesivamente. Por ejemplo, para acceder al elemento en la primera fila y la segunda columna de la matriz, podemos utilizar el siguiente código:

In [23]:
elemento = matriz[0][1]

También podemos utilizar la función len para obtener el número de filas y columnas de la matriz:

In [24]:
num_filas = len(matriz)
num_columnas = len(matriz[0])

Podemos realizar operaciones aritméticas con matrices utilizando bucles for. Por ejemplo, el siguiente código suma dos matrices:

In [25]:
# Definimos las matrices a sumar
matriz1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

# Creamos una matriz vacía del mismo tamaño que las matrices originales
suma = []
for i in range(len(matriz1)):
    fila = []
    for j in range(len(matriz1[0])):
        fila.append(0)
    suma.append(fila)

# Realizamos la suma de cada elemento correspondiente en ambas matrices
for i in range(len(matriz1)):
    for j in range(len(matriz1[0])):
        suma[i][j] = matriz1[i][j] + matriz2[i][j]

# Imprimimos la matriz resultante
print(suma)


[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


**Nota**: Si bien, las listas pueden utilizarse para crear vectores y matrices, para operaciones matemáticas se recomienda trabajar con la librería numpy y arrays, dado que se optimiza el uso de cómputo y se cuenta con métodos depurados para operaciones matemáticas y algebráicas.

Developed by:

- Brian Patino Agudelo - bpatinoa@unal.edu.co

- Andrés Marino Álvarez Meza - amalvarezme@unal.edu.co

- César Germán Castellanos Domínguez - cgcastellanosd@unal.edu.co